# Generated by Django 6.0.6 on 2026-07-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('education', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('interests', models.TextField()),
                ('strengths', models.TextField()),
                ('career_goal', models.CharField(max_length=100)),
                ('learning_preference', models.CharField(max_length=100)),
                ('challenge', models.CharField(max_length=200)),
                ('dream_career', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
