# Generated by Django 6.0.6 on 2026-07-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassessment',
            name='match_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='recommended_career',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='recommended_skills',
            field=models.TextField(blank=True),
        ),
    ]
